# Generated by Django 4.1.2 on 2022-10-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_lyric_song_song_artiste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song',
            new_name='song_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste',
            new_name='artiste_id',
        ),
    ]
