# Generated by Django 4.1.2 on 2022-10-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_lyric_song_song_artiste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song_id',
            new_name='songs_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='artist_id',
        ),
    ]
