# Generated by Django 4.1.2 on 2022-10-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_rename_songs_id_lyric_id_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='id_song',
            new_name='music_id',
        ),
    ]
