# Generated by Django 4.1.2 on 2022-10-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_rename_id_song_lyric_music_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='music_id',
            new_name='Song_idt',
        ),
    ]
