# Generated by Django 4.1.2 on 2022-10-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_rename_music_id_lyric_song_idt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='Song_idt',
            new_name='music_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artiste_id',
        ),
    ]
