# Generated by Django 4.1.2 on 2022-10-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_rename_song_idt_lyric_music_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='music_id',
            new_name='the_song_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='the_artiste_id',
        ),
    ]
