# Generated by Django 4.1.2 on 2022-10-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_rename_the_song_id_lyric_the_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='the_id',
            new_name='music_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='the_artiste_id',
            new_name='artiste_id',
        ),
    ]
