# Generated by Django 4.1.2 on 2022-10-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_rename_the_id_lyric_music_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='artist_id',
        ),
    ]
