# Generated by Django 4.1.2 on 2022-10-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0013_rename_music_id_lyric_song_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='Song_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='Artiste_id',
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
        ),
        migrations.AddField(
            model_name='lyric',
            name='song_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
            preserve_default=False,
        ),
    ]
